---
- hosts: localhost
  tasks:
    - debug:
        msg: "addition{{ 4 +3 }}" #Ansible addition 7
    - debug:
        msg: "substraction {{ 4 - 3 }}"  #Ansible arithmetic substraction 1
    - debug:
        msg: "multiplication {{ 4 * 3 }}" #multiplication 12
    - debug:
        msg: "Modulo operation {{ 7 % 4}}" #ansible Modulo operation - find remainder 3  - debug:
        msg: "floating division {{ 4 / 3}}" #ansible floating division 1.33333333333
    - debug:
        msg: "cube root {{ 27 | root(3)}}" # Ansible arithmetic cube root 3.0
    - debug:
        msg: "power {{ 3 | pow(3)}}" #Ansible arithmetic power of a number 27
    - debug: 
        msg: "Common Ansible round of a number {{ 39.7 | round}}" #40
                                                                                                                                  
