--- # Loop Playbook 
-  hosts: localhost
   become: yes
   tasks:
     - name: add a list of users
       user: name={{ item }} groups=wheel state=present
       with_items:
         - user1
         - user2
